name: Go

on:
  schedule:
    - cron: '05 21 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: |
          go get -v gopkg.in/gomail.v2
          go get -v github.com/n0madic/twitter-scraper

      - name: Run main.go
        run: |
          cd gorun
          go run main.go

