name: Go

on:
  schedule:
    - cron: '02 21 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        run: |
          wget -q -O go.tar.gz https://golang.org/dl/go1.19.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Run main.go
        run: go run main.go
